import { faviconSvg } from "@pragma-sh/brand";

export const size = { width: 32, height: 32 };
export const contentType = "image/svg+xml";

/** Serves the theme-aware Pragma favicon generated by `@pragma-sh/brand`. */
export default function Icon() {
  return new Response(faviconSvg(), {
    headers: { "Content-Type": contentType },
  });
}
