/** Gateway HTTP route builders. */
export const routes = {
  health: "/v1/health",
  version: "/v1/version",
  rpc: (method: string): string => `/v1/rpc/${encodeURIComponent(method)}`,
  sessions: "/v1/sessions",
  sessionEvents: (id: string): string => `/v1/sessions/${encodeURIComponent(id)}/events`,
  sessionInput: (id: string): string => `/v1/sessions/${encodeURIComponent(id)}/input`,
  sessionResize: (id: string): string => `/v1/sessions/${encodeURIComponent(id)}/resize`,
  session: (id: string): string => `/v1/sessions/${encodeURIComponent(id)}`,
  agentReports: "/v1/agents/reports",
  agentMessages: "/v1/agents/messages",
  agentAnswers: "/v1/agents/answers",
  agentDecisions: "/v1/agents/decisions",
  agentInputs: "/v1/agents/inputs",
  agentInterrupts: "/v1/agents/interrupts",
  agentCatalog: "/v1/agents/catalog",
  agentEvents: "/v1/agents/events",
  asset: (hash: string): string => `/v1/assets/${encodeURIComponent(hash)}`,
  agentsSeen: (tabId: string): string => `/v1/tabs/${encodeURIComponent(tabId)}/agents/seen`,
  subscription: (event: string): string => `/v1/subscriptions/${encodeURIComponent(event)}`,
  control: (method: string): string => `/v1/control/${encodeURIComponent(method)}`,
  pushTokens: "/v1/push/tokens",
  pushTest: "/v1/push/test",
  pushPresence: "/v1/push/presence",
} as const;
