#!/usr/bin/env bun
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Bakes this package's own `package.json` version into a generated module so
 * `definePlugin` can stamp every plugin with the `@pragma/plugin` version it
 * was compiled against, without plugin authors ever writing a version field
 * themselves. Mirrors `packages/constants`'s codegen-from-source-of-truth
 * convention; output lives under `src/generated/`, which is gitignored.
 */
async function main(): Promise<void> {
  const here = dirname(fileURLToPath(import.meta.url));
  const packageJsonPath = join(here, "..", "package.json");
  const packageJson = JSON.parse(await Bun.file(packageJsonPath).text()) as {
    version: string;
  };

  const outPath = join(here, "..", "src", "generated", "version.ts");
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(
    outPath,
    [
      "// Generated by scripts/generate-version.ts — do not edit by hand.",
      "/**",
      " * The `@pragma/plugin` version a plugin was compiled against, stamped onto",
      " * every plugin definition by `definePlugin`. Used by the Pragma host to check",
      " * compatibility before loading a plugin bundle.",
      " */",
      `export const PLUGIN_API_VERSION = ${JSON.stringify(packageJson.version)};`,
      "",
    ].join("\n"),
  );
}

await main();
