/// <reference types="node" />
/**
 * Two-stage build, mirroring `@pragma-sh/scratchpad-viewer`.
 *
 * 1. esbuild bundles `src/runtime/main.ts` — xterm and its addons — into one
 *    IIFE, and reads xterm's stylesheet, writing both out as a TypeScript
 *    module of string constants. The document this package produces has no
 *    network and no module loader, so the runtime has to arrive inline; string
 *    constants are what let a native client ship it with no bundler of its own.
 * 2. bunup emits the package's own ESM/CJS/`.d.ts` output.
 *
 * esbuild rather than `Bun.build` on purpose: Bun's Windows bundler panics on
 * `node_modules` paths outside the entry root, which is what bundling workspace
 * deps does — see `packages/scratchpad/AGENTS.md`.
 */
import { spawnSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

import { build } from "esbuild";

const OUTPUT = "src/generated/runtime-script.ts";
const BANNER = "/* AUTO-GENERATED by scripts/build.ts. Do not edit. */";

const bundle = await build({
  entryPoints: ["src/runtime/main.ts"],
  bundle: true,
  format: "iife",
  target: ["safari16", "chrome110"],
  platform: "browser",
  minify: true,
  write: false,
  define: { "process.env.NODE_ENV": '"production"' },
  logLevel: "warning",
});

const code = bundle.outputFiles[0]?.text;
if (!code) throw new Error("terminal viewer runtime produced no output");

const require = createRequire(import.meta.url);
const xtermDir = dirname(require.resolve("@xterm/xterm/package.json"));
const styles = await readFile(join(xtermDir, "css", "xterm.css"), "utf8");

// Both strings are embedded in elements whose content ends at the first
// `</script` / `</style`; escaping the slash keeps them semantically identical.
const module = [
  BANNER,
  `export const TERMINAL_RUNTIME_SCRIPT = ${JSON.stringify(code.replaceAll("</script", "<\\/script"))};`,
  `export const TERMINAL_RUNTIME_STYLES = ${JSON.stringify(styles.replaceAll("</style", "<\\/style"))};`,
  "",
].join("\n");

const existing = await readFile(OUTPUT, "utf8").catch(() => undefined);
if (existing !== module) {
  await mkdir("src/generated", { recursive: true });
  await writeFile(OUTPUT, module);
}

if (process.argv.includes("--runtime-only")) process.exit(0);

const result = spawnSync(
  process.execPath,
  [
    "x",
    "bunup",
    "src/index.ts",
    "--format",
    "esm,cjs",
    "--target",
    "browser",
    "--dts",
    "--no-splitting",
  ],
  { cwd: process.cwd(), env: { ...process.env, NODE_ENV: "production" }, stdio: "inherit" },
);

if (result.error) throw result.error;
if (result.status !== 0) process.exit(result.status ?? 1);
