/// <reference types="node" />
/**
 * Two-stage build.
 *
 * 1. esbuild bundles `src/runtime/main.tsx` — React, the MDX compiler, and the
 *    `@pragma/scratchpad` components — into one IIFE, which is written out as a
 *    TypeScript module exporting it as a string. The document this package
 *    produces has no network and no module loader, so the runtime has to arrive
 *    inline; a string constant is what lets a native client ship it with no
 *    bundler of its own and no asset to resolve at run time.
 * 2. bunup emits the package's own ESM/CJS/`.d.ts` output, with that generated
 *    module already in place.
 *
 * esbuild rather than `Bun.build` on purpose: Bun's Windows bundler panics
 * ("Expected pretty file path to have only forward slashes") on `node_modules`
 * paths outside the entry root, which is exactly what bundling workspace deps
 * does — see `packages/scratchpad/AGENTS.md`.
 */
import { spawnSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";

import { build } from "esbuild";

const OUTPUT = "src/generated/runtime-script.ts";
const BANNER = "/* AUTO-GENERATED by scripts/build.ts. Do not edit. */";

const bundle = await build({
  entryPoints: ["src/runtime/main.tsx"],
  bundle: true,
  format: "iife",
  target: ["safari16", "chrome110"],
  platform: "browser",
  jsx: "automatic",
  minify: true,
  write: false,
  define: { "process.env.NODE_ENV": '"production"' },
  logLevel: "warning",
});

const code = bundle.outputFiles[0]?.text;
if (!code) throw new Error("scratchpad viewer runtime produced no output");

// The string is embedded in a `<script>` element, so it must not carry a
// literal `</script`; escaping the slash keeps the JavaScript identical.
const escaped = code.replaceAll("</script", "<\\/script");
const module = `${BANNER}\nexport const VIEWER_RUNTIME_SCRIPT = ${JSON.stringify(escaped)};\n`;
const existing = await readFile(OUTPUT, "utf8").catch(() => undefined);
if (existing !== module) {
  await mkdir("src/generated", { recursive: true });
  await writeFile(OUTPUT, module);
}

if (process.argv.includes("--runtime-only")) process.exit(0);

const result = spawnSync(
  process.execPath,
  [
    "x",
    "bunup",
    "src/index.ts",
    "--format",
    "esm,cjs",
    "--target",
    "browser",
    "--dts",
    "--no-splitting",
  ],
  { cwd: process.cwd(), env: { ...process.env, NODE_ENV: "production" }, stdio: "inherit" },
);

if (result.error) throw result.error;
if (result.status !== 0) process.exit(result.status ?? 1);
