/// <reference types="node" />
/**
 * Shared steps of the workspace packages' `scripts/build.ts`.
 *
 * The viewer packages (`code-viewer`, `terminal-viewer`, `scratchpad-viewer`)
 * produce documents with no network and no module loader, so each bundles its
 * in-page runtime into one IIFE and writes it out as a TypeScript module of
 * string constants. Every package then emits its own ESM/CJS/`.d.ts` with bunup.
 *
 * esbuild rather than `Bun.build` on purpose: Bun's Windows bundler panics
 * ("Expected pretty file path to have only forward slashes") on `node_modules`
 * paths outside the entry root, which is exactly what bundling workspace deps
 * does — see `packages/scratchpad/AGENTS.md`.
 */
import { spawnSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

import { build } from "esbuild";

const BANNER = "/* AUTO-GENERATED by scripts/build.ts. Do not edit. */";

/** Bundles one browser runtime entry into a minified IIFE and returns its source. */
export async function bundleRuntime(
  entry: string,
  options: { jsx?: boolean } = {},
): Promise<string> {
  const bundle = await build({
    entryPoints: [entry],
    bundle: true,
    format: "iife",
    target: ["safari16", "chrome110"],
    platform: "browser",
    ...(options.jsx && { jsx: "automatic" as const }),
    minify: true,
    write: false,
    define: { "process.env.NODE_ENV": '"production"' },
    logLevel: "warning",
  });
  const code = bundle.outputFiles[0]?.text;
  if (!code) throw new Error(`${entry} produced no output`);
  return code;
}

/**
 * Escapes a string embedded in a `<script>` or `<style>` element, whose content
 * ends at the first `</script` / `</style`; escaping the slash keeps it
 * semantically identical.
 */
function escapeInline(source: string): string {
  return source.replaceAll("</script", "<\\/script").replaceAll("</style", "<\\/style");
}

/**
 * Writes a generated module of string constants, touching the file only when
 * its contents change so watchers and incremental builds stay quiet.
 */
export async function writeStringModule(
  output: string,
  constants: Record<string, string>,
): Promise<void> {
  const lines = Object.entries(constants).map(
    ([name, value]) => `export const ${name} = ${JSON.stringify(escapeInline(value))};`,
  );
  const module = [BANNER, ...lines, ""].join("\n");
  const existing = await readFile(output, "utf8").catch(() => undefined);
  if (existing === module) return;
  await mkdir(dirname(output), { recursive: true });
  await writeFile(output, module);
}

/** Whether this run should stop after regenerating the inline runtime. */
export function runtimeOnly(): boolean {
  return process.argv.includes("--runtime-only");
}

/**
 * Emits the package's ESM/CJS/`.d.ts` with bunup for the browser, exiting the
 * process with bunup's status when it fails.
 */
export function runBunup(entries: readonly string[], extraArgs: readonly string[] = []): void {
  const result = spawnSync(
    process.execPath,
    [
      "x",
      "bunup",
      ...entries,
      "--format",
      "esm,cjs",
      "--target",
      "browser",
      "--dts",
      "--no-splitting",
      ...extraArgs,
    ],
    { cwd: process.cwd(), env: { ...process.env, NODE_ENV: "production" }, stdio: "inherit" },
  );
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);
}
